# Generated by Django 5.1 on 2026-04-15 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('provider_name', models.CharField(max_length=200)),
                ('provider_logo', models.ImageField(blank=True, upload_to='offer_logos/')),
                ('category', models.CharField(choices=[('software', 'Software & Tools'), ('finance', 'Finance & Banking'), ('legal', 'Legal & Compliance'), ('marketing', 'Marketing & Design'), ('insurance', 'Insurance'), ('hr', 'HR & People'), ('other', 'Other')], default='other', max_length=20)),
                ('access_level', models.CharField(choices=[('all_members', 'All Members'), ('premium_only', 'Premium Only')], default='all_members', max_length=20)),
                ('short_description', models.CharField(max_length=300)),
                ('full_description', models.TextField()),
                ('discount_headline', models.CharField(help_text='e.g. "20% off all plans"', max_length=100)),
                ('redemption_url', models.URLField(blank=True)),
                ('redemption_code', models.CharField(blank=True, max_length=100)),
                ('redemption_instructions', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='offers.offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('offer', 'user')},
            },
        ),
    ]
