# Generated by Django 5.1 on 2026-04-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Free'), ('entry', 'Entry'), ('coaching', 'Coaching'), ('executive', 'Executive')], default='free', max_length=20),
        ),
    ]
