# Generated by Django 5.1 on 2026-04-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('logo', 'Logo'), ('colour_palette', 'Colour Palette'), ('typography', 'Typography'), ('templates', 'Templates'), ('guidelines', 'Guidelines'), ('other', 'Other')], default='other', max_length=30)),
                ('access_level', models.CharField(choices=[('all_members', 'All Members'), ('premium_only', 'Premium Only')], default='all_members', max_length=20)),
                ('file', models.FileField(upload_to='brand_assets/')),
                ('preview_image', models.ImageField(blank=True, upload_to='brand_assets/previews/')),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
